#!/bin/bash

echo "----------------------"
echo "starting script"
echo "current date / time:  "
echo "$(date)"
echo "----------------------"

echo "-----------------------"
echo "removing unneeded files"
echo "-----------------------"
sudo apt-get clean
sudo apt-get -y autoremove

####below is specific to mac users with a NAS who do not want the mac-generated files
echo "------------------------------------------"
echo "removing mac files that were autogenerated"
echo "------------------------------------------"
sudo find /srv/dev-disk-by-uuid-e790ab10-05b5-4446-be4f-761b1fdd1e7b/ -name ".DS_Store" -delete
sudo find /srv/dev-disk-by-uuid-e790ab10-05b5-4446-be4f-761b1fdd1e7b/ -name "._.DS_Store" -delete

echo "---------------------"
echo "updating raspberry pi"
echo "---------------------"
sudo apt-get update
echo "---------------------"
echo "upgrading raspberry pi"
echo "---------------------"
sudo apt-get -y upgrade
echo "----------------------------"
echo "dist-upgrade of raspberry pi"
echo "----------------------------"
sudo apt-get -y dist-upgrade

echo "---------------------------"
echo "ending script and rebooting"
echo "current date / time:  "
echo "$(date)"
echo "---------------------------"
sudo reboot
