#!/bin/bash

echo "----------------------"
echo "starting script"
echo "current date / time:  "
echo "$(date)"
echo "----------------------"

echo "-----------------------"
echo "removing unneeded files"
echo "$(date)"
echo "-----------------------"
sudo apt-get clean
sudo apt-get -y autoremove

####below is specific to mac users with a NAS who do not want the mac-generated files
echo "------------------------------------------"
echo "removing mac files that were autogenerated or unnecessary"
echo "$(date)"
echo "------------------------------------------"

#dev-disk-by-uuid-39be272b-862f-4c14-9d45-ff35eeb5fa11
#----main 4 TB WD Red
#dev-disk-by-uuid-6cbdec99-cc91-425c-8193-d1dee65a6fde
#----250 GB Crucial SSD
#dev-disk-by-uuid-b90d6365-9ba6-455b-9728-814f8a462ce1
#----backup 4TB WD Red
#dev-disk-by-uuid-e790ab10-05b5-4446-be4f-761b1fdd1e7b
#----500 GB Laptop HDD

##delete mac temp files from laptop 500GB hdd
sudo find /srv/dev-disk-by-uuid-e790ab10-05b5-4446-be4f-761b1fdd1e7b/ -name ".DS_Store" -delete
sudo find /srv/dev-disk-by-uuid-e790ab10-05b5-4446-be4f-761b1fdd1e7b/ -name "._.DS_Store" -delete
sudo find /srv/dev-disk-by-uuid-e790ab10-05b5-4446-be4f-761b1fdd1e7b/ -type f -name "._*" -delete
##delete mac temp files from main WD Red 4TB drive
sudo find /srv/dev-disk-by-uuid-39be272b-862f-4c14-9d45-ff35eeb5fa11/ -name ".DS_Store" -delete
sudo find /srv/dev-disk-by-uuid-39be272b-862f-4c14-9d45-ff35eeb5fa11/ -name "._.DS_Store" -delete
sudo find /srv/dev-disk-by-uuid-39be272b-862f-4c14-9d45-ff35eeb5fa11/media/photos/ -type f -name '*.jpeg_original' -delete
sudo find /srv/dev-disk-by-uuid-39be272b-862f-4c14-9d45-ff35eeb5fa11/ -type f -name "._*" -delete
##delete mac temp files from Crucial 250GB SSD
sudo find /srv/dev-disk-by-uuid-6cbdec99-cc91-425c-8193-d1dee65a6fde/ -name ".DS_Store" -delete
sudo find /srv/dev-disk-by-uuid-6cbdec99-cc91-425c-8193-d1dee65a6fde/ -name "._.DS_Store" -delete
sudo find /srv/dev-disk-by-uuid-6cbdec99-cc91-425c-8193-d1dee65a6fde/ -type f -name "._*" -delete

echo "---------------------"
echo "testing for .img creation weekly"
echo "$(date)"
echo "---------------------"
if [[ $(date -d "+1 day" +%m) != $(date +%m) ]]; then
    echo "it is the last day of the month so making a creation of the .img of the OS"

    dd if=/dev/sda of=/srv/dev-disk-by-uuid-39be272b-862f-4c14-9d45-ff35eeb5fa11/backups/computers/PI\ Backups/iso_backup/sd_card_backup_"`date +"%d-%m-%Y"`".img bs=1M

    echo "monthly creation of the .img of the OS completed"
fi


echo "---------------------"
echo "finished removing files from drives that are extra like ._DS_Store"
echo "$(date)"
echo "---------------------"
if [[ $(date +%u) -lt 7 ]]; then
    echo "it is not sunday so doing a non-delete backup of the extra files in the backup location"
    rsync -a /srv/dev-disk-by-uuid-39be272b-862f-4c14-9d45-ff35eeb5fa11/ /srv/dev-disk-by-uuid-b90d6365-9ba6-455b-9728-814f8a462ce1/backup-dev-disk-by-uuid-39be272b-862f-4c14-9d45-ff35eeb5fa11
    echo "rsync completed for the main 4TB drive"
    rsync -a /srv/dev-disk-by-uuid-6cbdec99-cc91-425c-8193-d1dee65a6fde/ /srv/dev-disk-by-uuid-b90d6365-9ba6-455b-9728-814f8a462ce1/backup-dev-disk-by-uuid-6cbdec99-cc91-425c-8193-d1dee65a6fde
    echo "rsync completed for the 250GB SSD"
fi

echo "---------------------"
echo "testing for rsync weekly"
echo "$(date)"
echo "---------------------"
if [[ $(date +%u) -gt 6 ]]; then
    echo "it is sunday so doing a weekly delete of the extra files in the backup location"
    rsync -a --delete /srv/dev-disk-by-uuid-39be272b-862f-4c14-9d45-ff35eeb5fa11/ /srv/dev-disk-by-uuid-b90d6365-9ba6-455b-9728-814f8a462ce1/backup-dev-disk-by-uuid-39be272b-862f-4c14-9d45-ff35eeb5fa11
    echo "rsync completed for the main 4TB drive"
    rsync -a --delete /srv/dev-disk-by-uuid-6cbdec99-cc91-425c-8193-d1dee65a6fde/ /srv/dev-disk-by-uuid-b90d6365-9ba6-455b-9728-814f8a462ce1/backup-dev-disk-by-uuid-6cbdec99-cc91-425c-8193-d1dee65a6fde
    echo "rsync completed for the 250GB SSD"
fi



echo "---------------------"
echo "updating raspberry pi"
echo "$(date)"
echo "---------------------"
sudo apt-get update
echo "---------------------"
echo "upgrading raspberry pi"
echo "$(date)"
echo "---------------------"
sudo apt-get -y upgrade
echo "----------------------------"
echo "dist-upgrade of raspberry pi"
echo "$(date)"
echo "----------------------------"
sudo apt-get -y dist-upgrade

echo "---------------------------"
echo "ending script and rebooting"
echo "current date / time:  "
echo "$(date)"
echo "---------------------------"
sudo reboot
